authnapp/urls.py
from django.urls import path

import authnapp.views as authnapp

app_name = "authnapp"

urlpatterns = [
    path("login/", authnapp.login, name="login"),
    path("logout/", authnapp.logout, name="logout"),
    path("register/", authnapp.register, name="register"),
    path("edit/", authnapp.edit, name="edit"),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", mainapp.main, name="main"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("contact/", mainapp.contact, name="contact"),
    path("auth/", include("authnapp.urls", namespace="auth")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = "mainapp"

urlpatterns = [
    path("", mainapp.products, name="index"),
    path("<int:pk>/", mainapp.products, name="category"),
]

authnapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to="users_avatars", blank=True)
    age = models.PositiveIntegerField(verbose_name="возраст")

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание", blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="имя продукта", max_length=128)
    image = models.ImageField(upload_to="products_images", blank=True)
    short_desc = models.CharField(verbose_name="краткое описание продукта", max_length=60, blank=True)
    description = models.TextField(verbose_name="описание продукта", blank=True)
    price = models.DecimalField(verbose_name="цена продукта", max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name="количество на складе", default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"


class Contact(models.Model):
    phone = models.CharField(max_length=50, verbose_name="номер телефона")
    email = models.EmailField(max_length=254, verbose_name="электронная почта")
    city = models.CharField(max_length=128, default="Москва", verbose_name="город")
    address = models.CharField(max_length=254, verbose_name="адресс")

    def __str__(self):
        return f"{self.pk} {self.email}"

authnapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm

from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = ShopUser
        fields = ("username", "password")


class ShopUserRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    def clean_age(self):
        data = self.cleaned_data["age"]
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data

    class Meta:
        model = ShopUser
        fields = ("username", "first_name", "password1", "password2", "email", "age", "avatar")


class ShopUserEditForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    def clean_age(self):
        data = self.cleaned_data["age"]
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

    class Meta:
        model = ShopUser
        fields = ("username", "first_name", "email", "age", "avatar")

authnapp/views.py
from django.conf import settings
from django.contrib import auth
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse

from authnapp.forms import ShopUserEditForm, ShopUserLoginForm, ShopUserRegisterForm


def login(request):
    title = "вход"

    login_form = ShopUserLoginForm(data=request.POST or None)
    if request.method == "POST" and login_form.is_valid():
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse("main"))

    content = {"title": title, "login_form": login_form}
    return render(request, "authnapp/login.html", content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("main"))


def register(request):
    title = "регистрация"

    if request.method == "POST":
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse("auth:login"))
    else:
        register_form = ShopUserRegisterForm()

    content = {"title": title, "register_form": register_form}
    return render(request, "authnapp/register.html", content)


def edit(request):
    title = "редактирование"

    if request.method == "POST":
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse("auth:edit"))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    content = {"title": title, "edit_form": edit_form, "media_url": settings.MEDIA_URL}
    return render(request, "authnapp/edit.html", content)

mainapp/views.py
from django.conf import settings
from django.shortcuts import render
from django.utils import timezone

from .models import Contact, Product, ProductCategory


def main(request):
    title = "главная"

    products = Product.objects.all()[:4]

    content = {"title": title, "products": products, "media_url": settings.MEDIA_URL}
    return render(request, "mainapp/index.html", content)


def products(request, pk=None):
    title = "продукты"
    links_menu = ProductCategory.objects.all()
    same_products = Product.objects.all()
    content = {
        "title": title,
        "links_menu": links_menu,
        "same_products": same_products,
        "media_url": settings.MEDIA_URL,
    }
    if pk:
        print(f"User select category: {pk}")
    return render(request, "mainapp/products.html", content)


def contact(request):
    title = "о нас"
    visit_date = timezone.now()
    locations = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "locations": locations}
    return render(request, "mainapp/contact.html", content)

authnapp/templates/authnapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock js %}

</head>

<body>
    <div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>

            {% block content %}
            {% endblock content %}

        </div>
    </div>
</body>

<script src="{% static 'js/bootstrap.min.js' %}"></script>

</html>

authnapp/templates/authnapp/edit.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

{% block content %}

<form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ edit_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
</form>
<button class="btn btn-round form-control last">
    <a href="{% url 'main' %}" class="">
        на главную
    </a>
</button>

{% if user.avatar %}
<div class="user_avatar"><img src="{{ media_url }}{{ user.avatar }}"></div>
{% endif %}

{% endblock %}

authnapp/templates/authnapp/login.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

{% block content %}

<form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
    {% csrf_token %}
    {{ login_form.as_p }}
    <br>
    <input class="form-control" type="submit" value="войти">
</form>
<button class="btn btn-round form-control">
    <a href="{% url 'auth:register' %}" class="">
        зарегистрироваться
    </a>
</button>

{% endblock content %}

authnapp/templates/authnapp/register.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

{% block content %}

<form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ register_form.as_p }}
    <br>
    <input class="form-control" type="submit" value="зарегистрироваться">
</form>

{% endblock %}

mainapp/templates/mainapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|capfirst }}
        {% endblock title %}
    </title>

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock css %}

    {% block js %}
    {% endblock js %}

</head>

<body>
    <div class="container">

        {% block menu %}
        {% endblock menu %}

        <div class="content">
        {% block content %}
        {% endblock content %}
        </div>

    </div>

    {% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
    {% endblock %}

</body>

</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block menu %}
<div class="hero">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_menu.html' %}
    </div>
    <h1>наши контакты</h1>
    <p>сегодня: {{ visit_date|date:"l, j F, Y" }}</p>
</div>
{% endblock %}

{% block content %}
<div class="location">
    {% for location in locations %}
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>{{ location.city }}</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>{{ location.phone }}</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>{{ location.email }}</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>{{ location.address }}</p>
        </div>
    </div>
    {% endfor %}
</div>

<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    {% for link in links_menu %}
    <li>
        <a href="{% url 'products:category' link.pk %}">
            {{ link.name }}
        </a>
    </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_menu.html
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    <li>
        <a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %}active{% endif %}">
            домой
        </a>
    </li>
    <li>
        <a href="{% url 'products:index' %}"
            class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
            контакты
        </a>
    </li>
    {% if user.is_authenticated %}
    <li>
        <a href="{% url 'auth:edit' %}">
            {{ user.first_name|default:'Пользователь' }}
        </a>
    </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
        <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>
</ul>
<a href="#" class="search"></a>
<a href="#" class="basket"></a>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block menu %}
<div class="slider">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_menu.html' %}
    </div>
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="#" class="button-order">
            заказать
            <img src="{% static 'img/arrow.png' %}" alt="">
        </a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>
{% endblock %}


{% block content %}
<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
    <div class="clearfix">
    </div>
    <div class="tab-content">
        {% for product in products %}
        <div class="block">
            <a href="{{ product.image }}"><img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
                <div class="text">
                    <img src="{% static 'img/icon-hover.png' %}" alt="img">
                    <h4>{{ product.name }}</h4>
                    <p>Описание: {{ product.description }} </p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_menu.html' %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{% static 'img/slider1.jpg' %}">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">Отличный стул</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> 2585.9 <span>руб</span></p>
			<a href="#" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				<p>Расположитесь комфортно.</p>
				<p>Отличное качество материалов
					позволит вам это.</p>
				<p>Различные цвета</p>
				<p>высочайший уровень
					эргономики и прочность.</p>
			</div>
		</div>
	</div>

    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="related-products clearfix">
            {% for product in same_products %}
			<div class="block">
    			<a href="#"><img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
        		<div class="text">
            		<img src="/static/img/icon-hover.png" alt="img">
					<h3>Категория:{{ product.category.name }}</h3>
					<h4>Название: {{ product.name }}</h4>
					<p>Описание: {{ product.description }} </p>
					<p>Цена: {{ product.price }} </p>
					<p>На складе: {{ product.quantity }} </p>
     		   </div>
 			   </a>
			</div>
			{% endfor %}
        </div>
    </div>
</div>

<div class="clr"></div>

{% endblock %}